feat: implement stale-while-revalidate via maxAge modification
swaglive/dio-http-cache pull request #1
Opened 2022-09-02 11:40 UTC by WJswag

2022-09-04 17:41 UTC, JimmyTai requested changes

2022-09-04 17:41 UTC, JimmyTai commented on lib/src/core/manager.dart
> +            DateTime.now().add(_serverTimeDiff).millisecondsSinceEpoch) {
要不要寫一個nowMilliseconds的getter

2022-09-04 17:43 UTC, JimmyTai commented
看起來除了`stale-while-revalidate`外還有2個cache-control的擴充，`immutable`和`stale-if-error`
需要也implement嗎？我們會用到嗎？

https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/Cache-Control#擴充_cache-control_指令

2022-09-05 05:53 UTC, JimmyTai approved these changes

2022-09-05 06:42 UTC, JimmyTai commented
@WJswag web在用的 http_dart_engine.dart 要不要也給cache-manager?

2022-09-05 08:12 UTC, WJswag commented
close https://github.com/swaglive/swag-flutter/issues/1237

2022-09-05 09:18 UTC, WJswag commented
> @WJswag ~web在用的 http_dart_engine.dart 要不要也給cache-manager?~ 好像browser應該會自動處理

yes

2022-09-05 09:19 UTC, WJswag commented
> 看起來除了`stale-while-revalidate`外還有2個cache-control的擴充，`immutable`和`stale-if-error` 需要也implement嗎？我們會用到嗎？
> 
> [https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/Cache-Control#擴充_cache-control_指令](https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/Cache-Control#%E6%93%B4%E5%85%85_cache-control_%E6%8C%87%E4%BB%A4)

2022-09-05 09:28 UTC, WJswag commented
> 看起來除了`stale-while-revalidate`外還有2個cache-control的擴充，`immutable`和`stale-if-error` 需要也implement嗎？我們會用到嗎？
> 
> [https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/Cache-Control#擴充_cache-control_指令](https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/Cache-Control#%E6%93%B4%E5%85%85_cache-control_%E6%8C%87%E4%BB%A4)

*stale-if-error* 也許會需要, 但我們比較多的狀況是error就不要stale response了, 還是先別放進來, 我看這個keyword還比較多人實作, 之後需要時可以直接import

*immutable* 使用場景不太像app會有的行為,  我們沒有refresh button可以給使用者整頁刷新
https://bitsup.blogspot.com/2016/05/cache-control-immutable.html

所以都先不implement

2023-05-18 03:34 UTC, JimmyTai commented
Close due to commits had been merged to swag-master branch.

2023-05-18 03:34 UTC, closed without merging